### ISSUE TITLE
Copied Plugin

### ISSUE THREAD

**Issue by CaptainDuck** [Epicrafter60/SurvivalGames#1]
Copied Plugin from @ImagicalGamer's SurvivalGames, i have downloaded and ported it from pmt.mcpe.me here is the zip file download link, http://pmt.mcpe.me/data/phars/zip_SurvivalGames_Red_v2.0.8_3eFVQ_i747nFKav.zip, Sorry dude, i hate liars..

**Comment by Epicrafter60** [comment]
Some people told me to bring it back cuz they wanted the sg v2 over the sg
v3 so don't blame me...

**Comment by CaptainDuck** [comment]
Who? Why didn't u give any credits or mentions from the REAL creator? Any proof of what ure saying? And read my DM I sent u.. Liar

**Comment by CaptainDuck** [comment]
U liar.. https://github.com/Epicrafter60/SurvivalGames/blob/master/README.md#credits "Inspiring me to make this plugin, HUH"

**Comment by ImagicalGamer** [comment]
Really dude, can you take it down or do I need to file another DCMA takedown request with @github?

**Comment by Thunder33345** [comment]
there is this thing called forking but WAIT A SEC git hub isnt for uncompiled files TBH

**Comment by ImagicalGamer** [comment]
Theirs forking and then what he did, give me creds and ur fine idc.

**Comment by CaptainDuck** [comment]
Nvm.. I was just proving that Epic can't code.. LOL.. "Self-taught PHP Programmer?!
